### PR TITLE
Add a processPath function to an options parameter for copy to manipulate destination path

### PR DESCRIPTION
**Pull request by asmagin**
Simplify #106 manipulation of a target path
Addresses #125

### CODE REVIEW

**Comment by asmagin** [comment]
Tests are failing due to #111

**Comment by asmagin** [comment]
Provides workaround for https://github.com/yeoman/yo/issues/577

**Comment by asmagin** [comment]
@SBoudrias any feedback?

**Comment by asmagin** [comment]
First of all, it is cleaner as you already have a `copyTpl` function that uses templating engine and it was passing process function to `copy`

Second, with this one I could use any templating engine, plain string replace or regex.

I've added comments to #106.

**Comment by nevir** [comment]
This would be helpful for keeping tooling sane in a repo with ejs templates (e.g. prettier, and other code formatters/linters).

For example, I'd like to have files with ejs template expressions suffixed with `.ejs`, but strip that suffix when copying files

**Pull request closed without merging**
