### PR TITLE
lower copy's zero check level when from is glob pattern

### PR DESCRIPTION
**Pull request by tarol**
fix eslint error passingly

### CODE REVIEW

**Comment by SBoudrias** [comment]
Can you explain the use case to allow glob to not match any files? In which case is this really useful?

**Comment by tarol** [comment]
English is not my native language; please excuse typing errors.
i use this package in yeoman-generator
my scaffold has serveral projects, but them use the same writing function
this function handle files according to the suffix, such as .ejs、.less、.js
i use glob pattern in this function to distinguish files, but one of project maybe has no .ejs files, then throw the error
i dont think this error should be throw, because glob pattern matched no files is a latent rule

**Comment by SBoudrias** [comment]
Note: fix #104

**Comment by SBoudrias** [comment]
Hey @tarol are you still planning to make changes and have this PR merged?

**Pull request closed without merging**
