### PR TITLE
Change `copyTpl` to have the same function signature as `copy` so it canaccept more options

### LINKED ISSUE #25: copyTpl should support glob options
the copyTpl function should support an optional options property in the same way that copy does.  More spicificly there should be some way to pass in globing options to paths that support globs.

### PR DESCRIPTION
**Pull request by blai**
Fixes #25

### CODE REVIEW

**Comment by blai** [comment]
@SBoudrias The API change is a breaking change.

**Comment by SBoudrias** [comment]
Hum, I'm not sure about this one... That's a very major breaking change.

**Comment by blai** [comment]
We could, but I think this make things more consistent.

**Comment by SBoudrias** [comment]
Would it be sufficient to only allow passing glob object as path? (ref #26)

**Comment by blai** [comment]
Actually I think that's an option too.

**Comment by SBoudrias** [comment]
Yeah, because this is too big of a breaking change. We wouldn't be able to bump it in Yeoman any time soon...

**Comment by SBoudrias** [comment]
I'll close this PR as we won't follow on this code path. Thanks for the work anyway!

**Comment by blai** [comment]
NP :) I will try to find time to implemented what we agree on.

**Pull request closed without merging**
