### PR TITLE
isbinaryfile does not follow semver for supported node, use fixed version

### PR DESCRIPTION
**Pull request by mshima**
Use fixed version to avoid conflicts in the future

node v14 and v16 support were dropped in a patch version.

### CODE REVIEW

**Comment by SBoudrias** [comment]
Want to release this one and then do a major release with latest? I doubt we want to keep 14/16 compat going forward.

**Comment by mshima** [comment]
We already dropped node 14/16 in current major.

**Comment by mshima** [comment]
But this causes https://github.com/yeoman/yo/issues/785#issuecomment-2023023839.

**Comment by SBoudrias** [comment]
Ah I see. The problem IMO is it'll be a game of whack a mole, if not this dependency, it'll be another one or anywhere through another transitive dep. It's hard to maintain support outside LTS Node version. (no concern fixing this here, but in the grand scheme of things, I don't think it'll have a big impact on users)

**Comment by mshima** [comment]
Yes, I'm just avoiding breaking in the future, I don't plan to release another v9 and v10.

**Pull request merged**
